# Generated by Django 5.2.4 on 2025-07-12 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created_at',
            new_name='created_time',
        ),
    ]
